import { CaretPluginSettings } from './types';

export const DEFAULT_SETTINGS: CaretPluginSettings = {
    caret_version: '0.2.30',
    chat_logs_folder: 'caret/chats',
    chat_logs_date_format_bool: false,
    chat_logs_rename_bool: true,
    chat_send_chat_shortcut: 'enter',
    model: 'gpt-4-turbo',
    llm_provider: 'openai',
    openai_api_key: '',
    groq_api_key: '',
    anthropic_api_key: '',
    open_router_key: '',
    context_window: 128000,
    custom_endpoints: {},
    system_prompt: '',
    temperature: 1,
    llm_provider_options: {
        openai: {
            'gpt-4-turbo': {
                name: 'gpt-4-turbo',
                context_window: 128000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            'gpt-3.5-turbo': {
                name: 'gpt-3.5-turbo',
                context_window: 128000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            'gpt-4o': {
                name: 'gpt-4o',
                context_window: 128000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
        },
        groq: {
            'llama3-8b-8192': {
                name: 'Llama 8B',
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            'llama3-70b-8192': {
                name: 'Llama 70B',
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            'mixtral-8x7b-32768': {
                name: 'Mixtral 8x7b',
                context_window: 32768,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            'gemma-7b-it': {
                name: 'Gemma 7B',
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
        },
        anthropic: {
            'claude-3-opus-20240229': {
                name: 'Claude 3 Opus',
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: false,
            },
            'claude-3-sonnet-20240229': {
                name: 'Claude 3 Sonnet',
                context_window: 200000,
                function_calling: true,
                vision: false,
                streaming: false,
            },
            'claude-3-haiku-20240307': {
                name: 'Claude 3 Haiku',
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: false,
            },
        },
        openrouter: {
            'anthropic/claude-3-opus': {
                name: 'Claude 3 Opus',
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            'anthropic/claude-3-sonnet': {
                name: 'Claude 3 Sonnet',
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            'anthropic/claude-3-haiku': {
                name: 'Claude 3 Haiku',
                context_window: 200000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            'google/gemini-flash-1.5': {
                name: 'Gemini Flash 1.5',
                context_window: 2800000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
            'google/gemini-pro-1.5': {
                name: 'Gemini Pro 1.5',
                context_window: 2800000,
                function_calling: true,
                vision: true,
                streaming: true,
            },
        },
        ollama: {
            llama3: {
                name: 'llama3 8B',
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            phi3: {
                name: 'Phi-3 3.8B',
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            mistral: {
                name: 'Mistral 7B',
                context_window: 32768,
                function_calling: false,
                vision: false,
                streaming: true,
            },
            gemma: {
                name: 'Gemma 7B',
                context_window: 8192,
                function_calling: false,
                vision: false,
                streaming: true,
            },
        },
        custom: {},
    },
    provider_dropdown_options: {
        openai: 'OpenAI',
        groq: 'Groq',
        ollama: 'Ollama',
        anthropic: 'Anthropic',
        openrouter: 'OpenRouter',
        custom: 'Custom',
    },
};
